const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
// Test the actual parser and converter bundled in the single HTML page.
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match => match[1]);
assert.equal(scripts.length, 2);
const context = {URL};
context.window = context;
vm.createContext(context);
vm.runInContext(scripts[0], context);
vm.runInContext(scripts[1].split('// Connect the page controls.')[0], context);
const convert = md => context.convertMarkdown(md);
let count = 0;
function ok(md, pattern) {
  const result = convert(md);
  assert.equal(result.issues.length, 0, JSON.stringify(result.issues));
  if (pattern) assert.match(result.fragment, pattern);
  count++;
  return result.fragment;
}
function bad(md, message) {
  const result = convert(md);
  assert(result.issues.some(item => item.message.includes(message)), JSON.stringify(result));
  assert.equal(result.fragment, undefined);
  count++;
}
ok('# Purpose\n\n## Step 1\n\n### Step 1.A', /font-size:24px/);
ok('**bold _italic_** and __bold__ and *italic* and _italic_', /<strong[^>]*>bold <em/);
ok('[**formatted** link](https://example.com/a_(b)?x=1&y=2)', /href="https:\/\/example.com\/a_\(b\)\?x=1&amp;y=2"/);
ok('Use `plain text` here.', /Use plain text here/);
ok('Use `<script>alert(1)</script>` here.', /&lt;script&gt;alert\(1\)&lt;\/script&gt;/);
ok('Use ``a `backtick` inside`` here.', /a `backtick` inside/);
ok('*\"Keep the quotation marks\"*', /&quot;Keep the quotation marks&quot;|"Keep the quotation marks"/);
ok('**A & B**', /A &amp; B/);
ok('[Email](mailto:person@example.com) and [Phone](tel:+1234567)');
ok('<https://example.com>');
ok('First\r\n\r\n# Purpose');
ok('A & B < 3 > 2', /A &amp; B &lt; 3 &gt; 2/);
ok('Escaped \\*literal\\* and file_name_here', /\*literal\* and file_name_here/);
ok('A paragraph\nwrapped on a new line.\n\nNext paragraph.', /A paragraph\nwrapped/);
ok('First  \nSecond', /<br>/);
ok('- First\n  1. Nested number\n     - Nested bullet\n- Second', /<li[^>]*>\n<p[^>]*>First<\/p>\n<ol/);
ok('5. Fifth\n6. Sixth', /start="5"/);
ok('+ One\n+ Two');
ok('[reference][site]\n\n[site]: https://example.com "Site"', /title="Site"/);
ok('[web](www.example.com)', /href="https:\/\/www.example.com\/"/);
ok('https://example.com', /<a /);
ok('Title\n=====\n\nSubtitle\n----', /<h2 /);
for (const heading of ['#### Deep','##### Deeper','###### Deepest']) bad(heading,'too deep');
for (const table of ['| A | B |\n|---|---|\n| x | y |','A | B\n--- | ---\nx | y']) bad(table, 'Tables');
for (const block of ['```js\nlet x=1\n```','~~~\ncode\n~~~','    code','- Item\n\n      code']) bad(block,'code');
bad('> Quote','Quotes');
bad('- Item\n  > Quote','Quotes');
bad('![alt](https://example.com/image.png)','Images');
bad('![alt][img]\n\n[img]: https://example.com/image.png','Images');
bad('~~gone~~','Strikethrough');
bad('---','Divider');
bad('<script>alert(1)</script>','HTML blocks');
bad('hello <img src=x onerror=alert(1)>','HTML tag');
bad('<u onclick="alert(1)">bad</u>','HTML tag');
bad('<u>underline</u>','HTML tags');
bad('</u>closing','HTML tags');
bad('[bad](javascript:alert(1))','link address');
bad('[bad](data:text/html,test)','link address');
bad('[bad](./relative)','link address');
bad('[bad](jav&#x61;script:alert(1))','link address');
bad('- [ ] Task','Checkbox');
bad('   ','Paste');
const lines = convert('# OK\n\n#### Too deep\n\n> Quote');
assert.deepEqual(Array.from(lines.issues, issue => issue.line), [3, 5]);
count++;
assert.match(ok('# Purpose'), /<h2[^>]*font-size:24px[^>]*color:#11599f/);
assert.match(ok('## Step'), /<h3[^>]*font-size:14pt[^>]*color:#11599f/);
assert.match(ok('### Substep'), /<p[^>]*font-size:16px[^>]*color:#000[^>]*><strong[^>]*>Substep<\/strong><\/p>/);
assert.match(ok(Array(30).fill('# Heading').join('\n')), /Heading/);
// Clipboard HTML must preserve the editor's heading types and list spacing.
const headings = ok('# Main\n\n## Step\n\n### Detail');
assert.doesNotMatch(headings, /<\/?h1\b/);
assert.match(headings, /<h2[^>]*>Main<\/h2>/);
assert.match(headings, /<h3[^>]*>Step<\/h3>/);
assert.match(headings, /<p[^>]*><strong[^>]*>Detail<\/strong><\/p>/);
assert.doesNotMatch(headings, /line-height:[\d.]+px/);
assert.equal((headings.match(/line-height:1.5/g) || []).length, 3);
assert.match(headings, /^<h2[^>]*margin-top:0;/);
assert.match(ok('Intro\n\n# Next section'), /<h2[^>]*margin:24px 0 0;[^>]*>Next section/);
const list = ok('- First\n- Second\n\n1. Number\n2. Another');
assert.equal((list.match(/<p[^>]*margin:0;/g) || []).length, 4);
assert.equal((list.match(/<li[^>]*margin:0 0 0 20px;/g) || []).length, 2);
assert.equal((list.match(/<li[^>]*margin:6px 0 0 20px;/g) || []).length, 2);
assert.match(ok('- First paragraph\n\n  Second paragraph'), /margin:16px 0 0;[^>]*>Second paragraph/);
console.log(`${count} converter checks passed.`);
